version: "3.1"

services:
  jetbrains-dev-container:
    image: jetbrains-dev-container
    build: src
    environment:
      SSH_USER: "${SSH_USER:-webdev}"
      TZ: "${TZ:-Etc/UTZ}"
    ports:
      - "${SSH_PORT:-22}:22"
